server:
    port: 8888
    servlet:
        context-path: /crm-server

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
    application:
        name: crm-server
    datasource:
        username: mailapp
        password: Qwerty321
        url: jdbc:postgresql://172.30.84.136:5432/mailapp
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

kgdIinBin:
    auth: "Basic VGVzdDEyMzpUZXN0MTIz"
    url: http://172.30.75.71:62669/iinbin/